### ISSUE TITLE
Can bbmap be used for mapping short contigs to reference genome?

### ISSUE THREAD

**Issue by nduan1** [BioInfoTools/BBMap#34]
Hi,

I am trying to extract viral information from metagenome, however, 95% of the assembled viral contigs were less than 10k, so I am thinking to map the short contigs(<10k) to the reference viral genome to get more long viral contigs, can I do this by bbmap.sh?

Thank you!

Ning

**Comment by epruesse** [comment]
Perhaps. Try using BLAST or MUMMER's NUCMER for this.

**Comment by nduan1** [comment]
Appreciate it! I will try to run it. 

Best,

Ning
